name: "CodeQL"

on:
  push:
    branches: [ master, develop ]
    paths:
      - 'openmp/**'
      - 'CMakeLists.txt'
      
  pull_request:
    branches: [ master, develop ]
    paths:
      - 'openmp/**'
      - 'CMakeLists.txt'

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-20.04
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: cpp, c

    - name: Install OpenMP
      run: |
          sudo apt update
          sudo apt install -y libomp-dev

    - name: "CMake Build"
      uses: lukka/run-cmake@v3
      with:
        useVcpkgToolchainFile: false
        buildDirectory: "${{ github.workspace }}/build"
        cmakeListsTxtPath: "${{ github.workspace }}/CMakeLists.txt"
        cmakeAppendedArgs: "-GNinja -DCMAKE_BUILD_TYPE=Release --parallel $(nproc)"

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1
