name: autobuild

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Install OpenMP
        run: |
          sudo apt update
          sudo apt install -y libomp-dev

      - name: "CMake Build"
        uses: lukka/run-cmake@v3
        with:
          useVcpkgToolchainFile: false
          buildDirectory: "${{ github.workspace }}/build"
          cmakeListsTxtPath: "${{ github.workspace }}/CMakeLists.txt"
          cmakeAppendedArgs: "-GNinja -DCMAKE_BUILD_TYPE=Release --parallel $(nproc)"
      